<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jsonPath = public_path('assets/seeders/countries.json');

        if (!File::exists($jsonPath)) {
            $this->command->error("Countries JSON file not found at: {$jsonPath}");
            return;
        }

        $raw = json_decode(File::get($jsonPath), true);
        $countriesData = [];

        foreach ($raw as $entry) {
            if (isset($entry['type']) && $entry['type'] === 'table' && isset($entry['data'])) {
                $countriesData = $entry['data'];
                break;
            }
        }

        if (empty($countriesData)) {
            $this->command->error("No country records found in JSON file.");
            return;
        }

        // Dedicated phone codes mapping for all countries
        $phoneCodesMap = [
            'DZ' => '+213',
            'FR' => '+33',
            'TN' => '+216',
            'MA' => '+212',
            'EG' => '+20',
            'SA' => '+966',
            'AE' => '+971',
            'GB' => '+44',
            'US' => '+1',
            'CA' => '+1',
            'DE' => '+49',
            'ES' => '+34',
            'IT' => '+39',
            'TR' => '+90',
            'BR' => '+55',
            'GR' => '+30',
            'UY' => '+598',
            'AT' => '+43',
            'CF' => '+236',
            'PE' => '+51',
            'AU' => '+61',
            'HU' => '+36',
            'AR' => '+54',
            'PY' => '+595',
            'ML' => '+223',
            'GN' => '+224',
            'NG' => '+234',
            'NL' => '+31',
            'CI' => '+225',
            'SN' => '+221',
            'HK' => '+852',
            'SK' => '+421',
            'CL' => '+56',
            'CZ' => '+420',
            'PH' => '+63',
            'MG' => '+261',
            'IN' => '+91',
            'BJ' => '+229',
            'JP' => '+81',
            'BG' => '+359',
            'DK' => '+45',
            'KE' => '+254',
            'BF' => '+226',
            'CG' => '+242',
            'CH' => '+41',
            'BE' => '+32',
            'MX' => '+52',
            'VE' => '+58',
            'ZA' => '+27',
            'RS' => '+381',
            'EC' => '+593',
            'PT' => '+351',
            'PR' => '+1',
            'IS' => '+354',
            'SE' => '+46',
            'CD' => '+243',
            'CO' => '+57',
            'PF' => '+689',
            'FI' => '+358',
            'NO' => '+47',
            'CM' => '+237',
            'RU' => '+7',
            'TT' => '+1868',
            'PL' => '+48',
            'ZW' => '+263',
            'NA' => '+264',
            'CU' => '+53',
            'MY' => '+60',
            'MU' => '+230',
            'SG' => '+65',
            'CR' => '+506',
            'TW' => '+886',
            'ID' => '+62',
            'LT' => '+370',
            'HR' => '+385',
            'SI' => '+386',
            'LV' => '+371',
            'GT' => '+502',
            'RO' => '+40',
            'EE' => '+372',
            'KR' => '+82',
            'CN' => '+86',
            'GH' => '+233',
            'MW' => '+265',
            'NE' => '+227',
            'TH' => '+66',
            'AL' => '+355',
            'IE' => '+353',
            'BO' => '+591',
            'TG' => '+228',
            'ZM' => '+260',
            'LK' => '+94',
            'MK' => '+389',
            'UA' => '+380',
            'PA' => '+507',
            'BY' => '+375',
            'JM' => '+1876',
            'KZ' => '+7',
            'MD' => '+373',
        ];

        // Dedicated Arabic names mapping for high quality localization
        $arabicMap = [
            'DZ' => 'الجزائر',
            'FR' => 'فرنسا',
            'TN' => 'تونس',
            'MA' => 'المغرب',
            'EG' => 'مصر',
            'SA' => 'المملكة العربية السعودية',
            'AE' => 'الإمارات العربية المتحدة',
            'GB' => 'المملكة المتحدة',
            'US' => 'الولايات المتحدة الأمريكية',
            'CA' => 'كندا',
            'DE' => 'ألمانيا',
            'ES' => 'إسبانيا',
            'IT' => 'إيطاليا',
            'TR' => 'تركيا',
            'BR' => 'البرازيل',
            'GR' => 'اليونان',
            'UY' => 'الأوروغواي',
            'AT' => 'النمسا',
            'CF' => 'جمهورية أفريقيا الوسطى',
            'PE' => 'بيرو',
            'AU' => 'أستراليا',
            'HU' => 'المجر',
            'AR' => 'الأرجنتين',
            'PY' => 'باراغواي',
            'ML' => 'مالي',
            'GN' => 'غينيا',
            'NG' => 'نيجيريا',
            'NL' => 'هولندا',
            'CI' => 'ساحل العاج',
            'SN' => 'السنغال',
            'HK' => 'هونغ كونغ',
            'SK' => 'سلوفاكيا',
            'CL' => 'تشيلي',
            'CZ' => 'التشيك',
            'PH' => 'الفلبين',
            'MG' => 'مدغشقر',
            'IN' => 'الهند',
            'BJ' => 'بنين',
            'JP' => 'اليابان',
            'BG' => 'بلغاريا',
            'DK' => 'الدنمارك',
            'KE' => 'كينيا',
            'BF' => 'بوركينا فاسو',
            'CG' => 'الكونغو',
            'CH' => 'سويسرا',
            'BE' => 'بلجيكا',
            'MX' => 'المكسيك',
            'VE' => 'فنزويلا',
            'ZA' => 'جنوب أفريقيا',
            'RS' => 'صربيا',
            'EC' => 'الإكوادور',
            'PT' => 'البرتغال',
            'PR' => 'بورتوريكو',
            'IS' => 'آيسلندا',
            'SE' => 'السويد',
            'CO' => 'كولومبيا',
            'PF' => 'بولينيزيا الفرنسية',
            'FI' => 'فنلندا',
            'NO' => 'النرويج',
            'CM' => 'الكاميرون',
            'RU' => 'روسيا',
            'TT' => 'ترينيداد وتوباغو',
            'PL' => 'بولندا',
            'ZW' => 'زيمبابوي',
            'NA' => 'ناميبيا',
            'CU' => 'كوبا',
            'MY' => 'ماليزيا',
            'MU' => 'موريشيوس',
            'SG' => 'سنغافورة',
            'CR' => 'كوستاريكا',
            'TW' => 'تايوان',
            'ID' => 'إندونيسيا',
            'LT' => 'ليتوانيا',
            'HR' => 'كرواتيا',
            'SI' => 'سلوفينيا',
            'LV' => 'لاتفيا',
            'GT' => 'غواتيمالا',
            'RO' => 'رومانيا',
            'EE' => 'إستونيا',
            'KR' => 'كوريا الجنوبية',
            'CN' => 'الصين',
            'GH' => 'غانا',
            'MW' => 'ملاوي',
            'NE' => 'النيجر',
            'TH' => 'تايلاند',
            'AL' => 'ألبانيا',
            'IE' => 'أيرلندا',
            'BO' => 'بوليفيا',
            'TG' => 'توغو',
            'ZM' => 'زامبيا',
            'LK' => 'سريلانكا',
            'MK' => 'مقدونيا الشمالية',
            'UA' => 'أوكرانيا',
            'PA' => 'بنما',
            'BY' => 'بيلاروسيا',
            'JM' => 'جامايكا',
            'KZ' => 'كازاخستان',
            'MD' => 'مولدوفا',
        ];

        // Dedicated French native names mapping
        $frenchMap = [
            'DZ' => 'Algérie',
            'FR' => 'France',
            'TN' => 'Tunisie',
            'MA' => 'Maroc',
            'EG' => 'Égypte',
            'SA' => 'Arabie Saoudite',
            'AE' => 'Émirats Arabes Unis',
            'GB' => 'Royaume-Uni',
            'US' => 'États-Unis',
            'CA' => 'Canada',
            'DE' => 'Allemagne',
            'ES' => 'Espagne',
            'IT' => 'Italie',
            'TR' => 'Turquie',
            'BR' => 'Brésil',
            'GR' => 'Grèce',
            'UY' => 'Uruguay',
            'AT' => 'Autriche',
            'CF' => 'République Centrafricaine',
            'PE' => 'Pérou',
            'AU' => 'Australie',
            'HU' => 'Hongrie',
            'AR' => 'Argentine',
            'PY' => 'Paraguay',
            'ML' => 'Mali',
            'GN' => 'Guinée',
            'NG' => 'Nigéria',
            'NL' => 'Pays-Bas',
            'CI' => 'Côte d\'Ivoire',
            'SN' => 'Sénégal',
            'HK' => 'Hong Kong',
            'SK' => 'Slovaquie',
            'CL' => 'Chili',
            'CZ' => 'Tchéquie',
            'PH' => 'Philippines',
            'MG' => 'Madagascar',
            'IN' => 'Inde',
            'BJ' => 'Bénin',
            'JP' => 'Japon',
            'BG' => 'Bulgarie',
            'DK' => 'Danemark',
            'KE' => 'Kenya',
            'BF' => 'Burkina Faso',
            'CG' => 'Congo',
            'CH' => 'Suisse',
            'BE' => 'Belgique',
            'MX' => 'Mexique',
            'VE' => 'Venezuela',
            'ZA' => 'Afrique du Sud',
            'RS' => 'Serbie',
            'EC' => 'Équateur',
            'PT' => 'Portugal',
            'PR' => 'Porto Rico',
            'IS' => 'Islande',
            'SE' => 'Suède',
            'CO' => 'Colombie',
            'PF' => 'Polynésie française',
            'FI' => 'Finlande',
            'NO' => 'Norvège',
            'CM' => 'Cameroun',
            'RU' => 'Russie',
            'TT' => 'Trinité-et-Tobago',
            'PL' => 'Pologne',
            'ZW' => 'Zimbabwe',
            'NA' => 'Namibie',
            'CU' => 'Cuba',
            'MY' => 'Malaisie',
            'MU' => 'Maurice',
            'SG' => 'Singapour',
            'CR' => 'Costa Rica',
            'TW' => 'Taïwan',
            'ID' => 'Indonésie',
            'LT' => 'Lituanie',
            'HR' => 'Croatie',
            'SI' => 'Slovénie',
            'LV' => 'Lettonie',
            'GT' => 'Guatemala',
            'RO' => 'Roumanie',
            'EE' => 'Estonie',
            'KR' => 'Corée du Sud',
            'CN' => 'Chine',
            'GH' => 'Ghana',
            'MW' => 'Malawi',
            'NE' => 'Niger',
            'TH' => 'Thaïlande',
            'AL' => 'Albanie',
            'IE' => 'Irlande',
            'BO' => 'Bolivie',
            'TG' => 'Togo',
            'ZM' => 'Zambie',
            'LK' => 'Sri Lanka',
            'MK' => 'Macédoine du Nord',
            'UA' => 'Ukraine',
            'PA' => 'Panama',
            'BY' => 'Bélarus',
            'JM' => 'Jamaïque',
            'KZ' => 'Kazakhstan',
            'MD' => 'Moldavie',
        ];

        foreach ($countriesData as $item) {
            $alpha2 = trim($item['alpha2'] ?? '');
            if (empty($alpha2)) {
                continue;
            }

            $phoneCode = $item['phone_code'] ?? ($phoneCodesMap[$alpha2] ?? null);
            $arabicName = $arabicMap[$alpha2] ?? ($item['arabic_name'] ?? $item['name']);
            $nativeName = $frenchMap[$alpha2] ?? ($item['native_name'] ?? $item['name']);

            Country::updateOrCreate(
                ['alpha2' => $alpha2],
                [
                    'id' => (int)$item['id'],
                    'ulid' => $item['ulid'] ?? null,
                    'name' => $item['name'],
                    'native_name' => $nativeName,
                    'arabic_name' => $arabicName,
                    'nationality' => $item['nationality'] ?? null,
                    'nationality_ar' => $item['nationality_ar'] ?? null,
                    'nationality_en' => $item['nationality_en'] ?? null,
                    'alpha3' => $item['alpha3'] ?? null,
                    'numeric_code' => $item['numeric_code'] ?? null,
                    'currency_code' => $item['currency_code'] ?? null,
                    'phone_code' => $phoneCode,
                    'flag_url' => !empty($item['flag_url']) ? $item['flag_url'] : 'https://flagcdn.com/' . strtolower($alpha2) . '.svg',
                    'is_active' => true,
                    'is_visible' => true,
                ]
            );
        }
    }
}
